Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 77, in emit
    self.doRollover()
  File "/usr/lib64/python2.6/logging/handlers.py", line 133, in doRollover
    os.remove(dfn)
OSError: [Errno 2] No such file or directory: '/software/mb/el6.3/python/envs/.virtualenvs/hook.log.1'
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file

INFO 	2016-05-29 14:14:38 	[trim_reads_trimmomatic] 	paths to read1 and read2 saved to metadata database
INFO 	2016-05-29 14:14:38 	[trim_reads_trimmomatic] 	sequencing type = PE
INFO 	2016-05-29 14:14:38 	[trim_reads_trimmomatic] 	trimming adapter sequences for HiSeq, NextSeq or HiSeq
INFO 	2016-05-29 14:14:38 	[trim_reads_trimmomatic] 	trimming low-quality reads ends using trimmomatic's recommended practices
