Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 77, in emit
    self.doRollover()
  File "/usr/lib64/python2.6/logging/handlers.py", line 133, in doRollover
    os.remove(dfn)
OSError: [Errno 2] No such file or directory: '/software/mb/el6.3/python/envs/.virtualenvs/hook.log.1'
Traceback (most recent call last):
  File "/usr/lib64/python2.6/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib64/python2.6/logging/handlers.py", line 150, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
ValueError: I/O operation on closed file
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1524, in shutdown
    h.flush()
  File "/usr/lib64/python2.6/logging/__init__.py", line 770, in flush
    self.stream.flush()
ValueError: I/O operation on closed file

Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "PIPELINE_RUN_MODE") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', 'full')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "QUEUE") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', 'long-sl65')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "MEMORY") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', '60G')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "MAX_TIME") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', '20:00:00')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "SLOTS") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', '8')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "ASSEMBLY_VERSION") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', 'hg38_mmtv')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "JOB_NAME") VALUES (?, ?)'] [parameters: ('gv_054_01_01_chipseq', 'chipseq-16.04')]
INFO 	2016-04-27 15:37:30 	[trim_reads_trimmomatic] 	paths to read1 saved to metadata database
INFO 	2016-04-27 15:37:30 	[trim_reads_trimmomatic] 	sequencing type = SE
INFO 	2016-04-27 15:37:30 	[trim_reads_trimmomatic] 	trimming adapter sequences for HiSeq, NextSeq or HiSeq
INFO 	2016-04-27 15:37:30 	[trim_reads_trimmomatic] 	trimming low-quality reads ends using trimmomatic's recommended practices
INFO 	2016-04-27 16:08:43 	[trim_reads_trimmomatic] 	parse step log to extract generated metadata
INFO 	2016-04-27 16:08:43 	[trim_reads_trimmomatic] 	reads after trimming = 107081217
INFO 	2016-04-27 16:09:03 	[trim_reads_trimmomatic] 	trimmomatic parameters and numbe of trimmed reads added to metadata
INFO 	2016-04-27 16:09:03 	[trim_reads_trimmomatic] 	trimmed reads are in /users/GR/mb/jquilez/data/chipseq/samples/gv_054_01_01_chipseq/fastqs_processed/trimmomatic/single_end
TIME 	2016-04-27 16:09:03 	[trim_reads_trimmomatic] 	step time for completion (seconds) = 1984

INFO 	2016-04-27 16:09:05 	[align_bwa] 	align single-end reads with BWA
INFO 	2016-04-27 16:09:05 	[align_bwa] 	alignments are converted to BAM, sorted by genomic coordinates and multi-mappings filtered out
[main] Version: 0.7.12-r1039
[main] CMD: /software/mb/el6.3/bwa/bwa-0.7.12/bwa mem -t 8 -M -R @RG\tID:'gv_054_01_01_chipseq'\tLB:'gv_054_01_01_chipseq'\tPL:illumina\tPU:'gv_054_01_01_chipseq'\tSM:'gv_054_01_01_chipseq' -v 0 /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYMUn.fa /users/GR/mb/jquilez/data/chipseq/samples/gv_054_01_01_chipseq/fastqs_processed/trimmomatic/single_end/gv_054_01_01_chipseq_read1.fastq.gz
[main] Real time: 5633.413 sec; CPU: 43418.638 sec
[bam_sort_core] merging from 45 files...
INFO 	2016-04-27 18:11:27 	[align_bwa] 	reads aligned = 107081217
INFO 	2016-04-27 18:11:27 	[align_bwa] 	reads unique = 82210418
INFO 	2016-04-27 18:11:32 	[align_bwa] 	path to genome sequence FASTA and number of (uniquely) aligned reads added to metadata
TIME 	2016-04-27 18:11:47 	[align_bwa] 	step time for completion (seconds) = 7362

INFO 	2016-04-27 18:11:49 	[quality_alignments] 	general QC of the BAM (using qualimap's bamqc)
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	parse step log to extract generated metadata
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	percentage duplication = 12.75
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	median insert size (bp) = 0
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	mean mapping quality = 44.977
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	mean coverage (X) = 0.9566
INFO 	2016-04-27 18:16:04 	[quality_alignments] 	mean coverage adjusted paired-end = .
TIME 	2016-04-27 18:16:12 	[quality_alignments] 	step time for completion (seconds) = 263

INFO 	2016-04-27 18:16:13 	[make_tag_directory] 	converting BAM to BED --required for making tag directory
INFO 	2016-04-27 18:19:45 	[make_tag_directory] 	make tag directory with HOMER
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	parse step log to extract generated metadata
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	estimated genome size = 3090892724
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	estimated average read density per bp = 0.026598
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	total tags = 82210418.0
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	total_positions = 72263866
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	avg. tag length = 36.0
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	median tags per position = 1
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	avg. tags per position = 1.138
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	fragment length estimate = 204
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	peak width estimate = 192
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	autocorrelation: same strand fold enrichment = 1.1
INFO 	2016-04-27 18:35:30 	[make_tag_directory] 	autocorrelation: diff strand fold enrichment = 1.1
INFO 	2016-04-27 18:35:31 	[make_tag_directory] 	autocorrelation: same-to-diff strand fold enrichment = 1.0
INFO 	2016-04-27 18:35:31 	[make_tag_directory] 	avg. fragment GC% = 43.76
INFO 	2016-04-27 18:35:31 	[make_tag_directory] 	avg. expected GC% = 40.58
INFO 	2016-04-27 18:35:52 	[make_tag_directory] 	ChIP-seq metrics calculated with Homer added to metadata
TIME 	2016-04-27 18:35:52 	[make_tag_directory] 	step time for completion (seconds) = 1179

INFO 	2016-04-27 18:35:53 	[make_profiles] 	generate reads per million profile (RPM) fragment profile
INFO 	2016-04-27 20:05:15 	[make_profiles] 	get fragment length estimate (l) as calculated in the 'make_tag_directory' step
INFO 	2016-04-27 20:05:15 	[make_profiles] 	fragment length estimate = 204
INFO 	2016-04-27 20:05:15 	[make_profiles] 	fragment length correction = 204
INFO 	2016-04-27 20:05:15 	[make_profiles] 	the correction will be used if the estimate is not reliable
TIME 	2016-04-27 20:05:19 	[make_profiles] 	step time for completion (seconds) = 5366

INFO 	2016-04-27 20:05:22 	[call_peaks] 	Get fragment length estimate (l) as calculated in the 'make_tag_directory' step
INFO 	2016-04-27 20:05:22 	[call_peaks] 	Fragment length (l) is 204 bp (note this is not used if peak caller is zerone)
INFO 	2016-04-27 20:05:22 	[call_peaks] 	Peak calling with MACS2
INFO 	2016-04-27 20:05:22 	[call_peaks] 	genome size for homo_sapiens will be used
INFO 	2016-04-27 20:05:22 	[call_peaks] 	q-value cutoff = 0.05 (default is 0.01)
INFO 	2016-04-27 20:05:22 	[call_peaks] 	--nomodel (MACS2 will not try to model peak length but use l = 204 instead
INFO 	2016-04-27 20:05:22 	[call_peaks] 	--call-summits = MACS reanalyzes the shape of signal profile to deconvolve subpeaks within each peak called
INFO 	2016-04-27 20:05:22 	[call_peaks] 	peak calling with the sample alone (i.e. no input)
INFO 	2016-04-27 20:15:50 	[call_peaks] 	peaks = 33324
INFO 	2016-04-27 20:15:57 	[call_peaks] 	peak calling without input DNA as control added to metadata

