Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1525, in shutdown
    h.close()
  File "/usr/lib64/python2.6/logging/__init__.py", line 844, in close
    self.stream.close()
IOError: [Errno 116] Stale file handle
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib64/python2.6/logging/__init__.py", line 1525, in shutdown
    h.close()
  File "/usr/lib64/python2.6/logging/__init__.py", line 844, in close
    self.stream.close()
IOError: [Errno 116] Stale file handle

Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "PIPELINE_RUN_MODE") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', 'full')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "QUEUE") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', 'long-sl65')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1166, in _execute_context
    self._root._commit_impl(autocommit=True)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 693, in _commit_impl
    self.connection._reset_agent is self.__transaction:
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 318, in connection
    self._handle_dbapi_exception(e, None, None, None, None)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1344, in _handle_dbapi_exception
    util.reraise(*exc_info)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 316, in connection
    return self._revalidate_connection()
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 396, in _revalidate_connection
    raise exc.ResourceClosedError("This Connection is closed")
sqlalchemy.exc.ResourceClosedError: This Connection is closed
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "MAX_TIME") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', '20:00:00')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "SLOTS") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', '8')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "ASSEMBLY_VERSION") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', 'hg38_mmtv')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "JOB_NAME") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', 'chipseq-16.04')]
Traceback (most recent call last):
  File "/users/GR/mb/jquilez/utils/io_metadata.py", line 101, in <module>
    tab.upsert(new_data, ['SAMPLE_ID'])
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 183, in upsert
    return self.insert(row, ensure=ensure, types=types)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/dataset/persistence/table.py", line 75, in insert
    res = self.database.executable.execute(self.table.insert(row))
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/nfs/software/mb/el6.3/python/envs/.virtualenvs/cpython279/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: u'INSERT INTO chipseq ("SAMPLE_ID", "PATH_JOB_FILE") VALUES (?, ?)'] [parameters: ('gv_017_01_01_chipseq', '/users/GR/mb/jquilez/pipelines/chipseq-16.04/job_cmd/gv_017_01_01_chipseq_2016_04_27_full_macs2_chipseq-16.04.sh')]
INFO 	2016-04-27 15:36:49 	[trim_reads_trimmomatic] 	paths to read1 saved to metadata database
INFO 	2016-04-27 15:36:49 	[trim_reads_trimmomatic] 	sequencing type = SE
INFO 	2016-04-27 15:36:49 	[trim_reads_trimmomatic] 	trimming adapter sequences for HiSeq, NextSeq or HiSeq
INFO 	2016-04-27 15:36:49 	[trim_reads_trimmomatic] 	trimming low-quality reads ends using trimmomatic's recommended practices
INFO 	2016-04-27 16:13:23 	[trim_reads_trimmomatic] 	parse step log to extract generated metadata
INFO 	2016-04-27 16:13:24 	[trim_reads_trimmomatic] 	reads after trimming = 95624344
INFO 	2016-04-27 16:13:51 	[trim_reads_trimmomatic] 	trimmomatic parameters and numbe of trimmed reads added to metadata
INFO 	2016-04-27 16:13:51 	[trim_reads_trimmomatic] 	trimmed reads are in /users/GR/mb/jquilez/data/chipseq/samples/gv_017_01_01_chipseq/fastqs_processed/trimmomatic/single_end
TIME 	2016-04-27 16:13:51 	[trim_reads_trimmomatic] 	step time for completion (seconds) = 2282

INFO 	2016-04-27 16:13:58 	[align_bwa] 	align single-end reads with BWA
INFO 	2016-04-27 16:13:58 	[align_bwa] 	alignments are converted to BAM, sorted by genomic coordinates and multi-mappings filtered out
[main] Version: 0.7.12-r1039
[main] CMD: /software/mb/el6.3/bwa/bwa-0.7.12/bwa mem -t 8 -M -R @RG\tID:'gv_017_01_01_chipseq'\tLB:'gv_017_01_01_chipseq'\tPL:illumina\tPU:'gv_017_01_01_chipseq'\tSM:'gv_017_01_01_chipseq' -v 0 /users/GR/mb/jquilez/assemblies/homo_sapiens/hg38_mmtv/ucsc/hg38_mmtv_chr1-22XYMUn.fa /users/GR/mb/jquilez/data/chipseq/samples/gv_017_01_01_chipseq/fastqs_processed/trimmomatic/single_end/gv_017_01_01_chipseq_read1.fastq.gz
[main] Real time: 3937.570 sec; CPU: 29960.964 sec
[bam_sort_core] merging from 48 files...
INFO 	2016-04-27 17:48:42 	[align_bwa] 	reads aligned = 95625367
INFO 	2016-04-27 17:48:42 	[align_bwa] 	reads unique = 82645924
INFO 	2016-04-27 17:48:47 	[align_bwa] 	path to genome sequence FASTA and number of (uniquely) aligned reads added to metadata
TIME 	2016-04-27 17:49:04 	[align_bwa] 	step time for completion (seconds) = 5706

INFO 	2016-04-27 17:49:05 	[quality_alignments] 	general QC of the BAM (using qualimap's bamqc)
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	parse step log to extract generated metadata
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	percentage duplication = 5.49
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	median insert size (bp) = 0
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	mean mapping quality = 43.843
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	mean coverage (X) = 1.3318
INFO 	2016-04-27 17:54:02 	[quality_alignments] 	mean coverage adjusted paired-end = .
TIME 	2016-04-27 17:54:10 	[quality_alignments] 	step time for completion (seconds) = 305

INFO 	2016-04-27 17:54:12 	[make_tag_directory] 	converting BAM to BED --required for making tag directory
INFO 	2016-04-27 17:58:17 	[make_tag_directory] 	make tag directory with HOMER
INFO 	2016-04-27 18:11:59 	[make_tag_directory] 	parse step log to extract generated metadata
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	estimated genome size = 3090951853
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	estimated average read density per bp = 0.026738
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	total tags = 82645924.0
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	total_positions = 78221755
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	avg. tag length = 49.8
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	median tags per position = 1
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	avg. tags per position = 1.057
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	fragment length estimate = 114
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	peak width estimate = 185
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	autocorrelation: same strand fold enrichment = 2.0
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	autocorrelation: diff strand fold enrichment = 1.9
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	autocorrelation: same-to-diff strand fold enrichment = 1.0
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	avg. fragment GC% = 42.03
INFO 	2016-04-27 18:12:00 	[make_tag_directory] 	avg. expected GC% = 40.35
INFO 	2016-04-27 18:12:20 	[make_tag_directory] 	ChIP-seq metrics calculated with Homer added to metadata
TIME 	2016-04-27 18:12:20 	[make_tag_directory] 	step time for completion (seconds) = 1088

INFO 	2016-04-27 18:12:22 	[make_profiles] 	generate reads per million profile (RPM) fragment profile
INFO 	2016-04-27 19:19:42 	[make_profiles] 	get fragment length estimate (l) as calculated in the 'make_tag_directory' step
INFO 	2016-04-27 19:19:42 	[make_profiles] 	fragment length estimate = 114
INFO 	2016-04-27 19:19:42 	[make_profiles] 	fragment length correction = 114
INFO 	2016-04-27 19:19:42 	[make_profiles] 	the correction will be used if the estimate is not reliable
TIME 	2016-04-27 19:19:45 	[make_profiles] 	step time for completion (seconds) = 4043

INFO 	2016-04-27 19:19:47 	[call_peaks] 	Get fragment length estimate (l) as calculated in the 'make_tag_directory' step
INFO 	2016-04-27 19:19:47 	[call_peaks] 	Fragment length (l) is 114 bp (note this is not used if peak caller is zerone)
INFO 	2016-04-27 19:19:47 	[call_peaks] 	Peak calling with MACS2
INFO 	2016-04-27 19:19:47 	[call_peaks] 	genome size for homo_sapiens will be used
INFO 	2016-04-27 19:19:47 	[call_peaks] 	q-value cutoff = 0.05 (default is 0.01)
INFO 	2016-04-27 19:19:47 	[call_peaks] 	--nomodel (MACS2 will not try to model peak length but use l = 114 instead
INFO 	2016-04-27 19:19:47 	[call_peaks] 	--call-summits = MACS reanalyzes the shape of signal profile to deconvolve subpeaks within each peak called
INFO 	2016-04-27 19:19:48 	[call_peaks] 	peak calling with the sample alone (i.e. no input)
INFO 	2016-04-27 19:31:13 	[call_peaks] 	peaks = 55510
INFO 	2016-04-27 19:31:20 	[call_peaks] 	peak calling without input DNA as control added to metadata

